export const members = [
  {
    id: "m1",
    name: "Chukwuma Mokwe",
    role: "Photographer & Video Editor",
    dept: "Media Production",
    contact: "",
  },
  {
    id: "m2",
    name: "David Okon",
    role: "Graphic Designer",
    dept: "Design",
    contact: "",
  },
  {
    id: "m3",
    name: "Daniel Itohan",
    role: "Graphic Designer",
    dept: "Design",
    contact: "",
  },
  {
    id: "m4",
    name: "Abubakar Segun Yusuf",
    role: "Social Media Manager",
    dept: "Social Media",
    contact: "",
  },
  {
    id: "m5",
    name: "Juliet Egbuniwe",
    role: "Social Media Manager",
    dept: "Social Media",
    contact: "",
  },
  {
    id: "m6",
    name: "Dara Stephen",
    role: "Social Media Manager",
    dept: "Social Media",
    contact: "",
  },
  {
    id: "m7",
    name: "Rakiba Yahaya",
    role: "Media Personnel",
    dept: "Media & PR",
    contact: "",
  },
];

const today = new Date();
const fmt = (d: Date) => d.toISOString().split("T")[0];
const addDays = (d: Date, n: number) => {
  let x = new Date(d);
  x.setDate(x.getDate() + n);
  return x;
};

export const initialTasks = [
  {
    id: "t1",
    name: "TEDxMaitama Event Photography Brief",
    member: "m1",
    priority: "High",
    start: fmt(addDays(today, -3)),
    deadline: fmt(addDays(today, 1)),
    pct: 60,
    status: "In Progress",
    desc: "Prepare shot list and brief for the TEDx event",
    actual: "",
    lateReason: "",
    feedback: "",
    quality: "",
  },
  {
    id: "t2",
    name: "Speaker Announcement Graphic (Dr. Bagudu)",
    member: "m2",
    priority: "High",
    start: fmt(addDays(today, -2)),
    deadline: fmt(addDays(today, -1)),
    pct: 100,
    status: "Completed",
    desc: "",
    actual: fmt(today),
    lateReason: "",
    feedback: "Excellent work",
    quality: "5 – Excellent",
  },
  {
    id: "t3",
    name: "TEDx Event Banner Design",
    member: "m3",
    priority: "Medium",
    start: fmt(addDays(today, -1)),
    deadline: fmt(addDays(today, 2)),
    pct: 30,
    status: "In Progress",
    desc: "",
    actual: "",
    lateReason: "",
    feedback: "",
    quality: "",
  },
  {
    id: "t4",
    name: "Instagram Content Calendar – March",
    member: "m4",
    priority: "High",
    start: fmt(addDays(today, -4)),
    deadline: fmt(addDays(today, -2)),
    pct: 50,
    status: "In Progress",
    desc: "",
    actual: "",
    lateReason: "Awaiting approval on content pillars",
    feedback: "",
    quality: "",
  },
  {
    id: "t5",
    name: "Twitter/X Engagement Post Series",
    member: "m5",
    priority: "Medium",
    start: fmt(today),
    deadline: fmt(addDays(today, 3)),
    pct: 0,
    status: "Not Started",
    desc: "",
    actual: "",
    lateReason: "",
    feedback: "",
    quality: "",
  },
  {
    id: "t6",
    name: "LinkedIn TEDx Announcement Post",
    member: "m6",
    priority: "High",
    start: fmt(addDays(today, -1)),
    deadline: fmt(today),
    pct: 80,
    status: "In Progress",
    desc: "",
    actual: "",
    lateReason: "",
    feedback: "",
    quality: "",
  },
  {
    id: "t7",
    name: "Press Release – TEDxMaitama Women",
    member: "m7",
    priority: "High",
    start: fmt(addDays(today, -3)),
    deadline: fmt(addDays(today, -1)),
    pct: 40,
    status: "In Progress",
    desc: "",
    actual: "",
    lateReason: "Waiting for final speaker confirmation",
    feedback: "",
    quality: "",
  },
];

export const initialLogs = [
  {
    id: "l1",
    member: "m1",
    date: fmt(today),
    completed: "Event Brief Draft",
    progress: "Contacting vendors",
    blockers: "",
    hours: "6",
  },
  {
    id: "l2",
    member: "m2",
    date: fmt(today),
    completed: "Speaker Graphics",
    progress: "Social banners",
    blockers: "Software license expired",
    hours: "8",
  },
];
